
# List all files colorized in long format, excluding . and ..
alias ll='ls -lAF --color'
# List all files colorized in short format, excluding . and ..
alias la='ls -A --color'
# List folder colorized in short format
alias l='ls -CF --color'

# Shortcuts
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias h="cd ~"
alias dw="cd ~/Downloads"
alias dot="cd ~/dev/dotfiles"
alias dl="cd ~/dev/dl"
alias my="cd ~/dev/my"
alias spikes="cd ~/dev/spikes"

# Commands
alias ld='lazydocker'

alias g="git"
alias m="make"
alias dk="docker"
alias dn="dotnet"

alias fd=fdfind
alias bat=batcat

alias mv="mvn"
alias mvci="mvn clean install"
alias mvcc="mvn clean compile"

# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'