export LANG=en_US.UTF-8

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

# Load the shell dotfiles
for file in ~/.{bash_aliases,bash_exports,bash_options,bash_prompt,bash_functions,bash_private}; do
    [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

# Enable some Bash features when possible:
# * `autocd`, e.g. `**/qux` will enter `./foo/bar/baz/qux`
# * Recursive globbing, e.g. `echo **/*.txt`
# * `cdspell` autocorrect typos, e.g. `cd mi` into `cd my`
for option in autocd globstar cdspell; do
	shopt -s "$option" 2> /dev/null;
done;

# Add tab completion for many Bash commands
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    source /etc/bash_completion
fi

# Source fzf
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# Enable docker buildkit
export DOCKER_BUILDKIT=1

. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash

# add JAVA_HOME
. $HOME/.asdf/plugins/java/set-java-home.bash

export DOTNET_CLI_TELEMETRY_OPTOUT=1

eval "$(starship init bash)"
eval `dircolors $HOME/.dir_colors`

[ -f "$HOME/.local/bin" ] && source "$HOME/.local/bin"
[ -f "$HOME/.ghcup/env" ] && source "$HOME/.ghcup/env"
